name: pragma
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter_riverpod: ^2.0.0-dev.6
  riverpod: ^2.0.0-dev.6
  equatable: ^2.0.3
  lottie: ^1.4.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/lottie_file/
    - assets/gif/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Lora
      fonts:
        - asset: assets/fonts/Lora-Italic-VariableFont_wght.ttf
        - asset: assets/fonts/Lora-VariableFont_wght.ttf
          

flutter_intl: 
  enabled: true
  main_locale: en
  class_name: I18n

